routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource('photo', 'PhotoController');
Route::resource('crawl', 'CrawlingController');

Route::group(['prefix'=>'/'],function(){
    Route::get('/',['as'=>'layouts.index', 'uses'=>'PostController@home']);
    Route::get('/single/{id}',['as'=>'singlePost', 'uses'=>'PostController@single']);
    Route::get('/category/{id}/posts',['as'=>'categoryPost', 'uses'=>'PostController@categoriesposts']);
    Route::get('/viewer/login/page','ViewerController@index')->name('viewer.index');
    Route::post('/viewer/login','ViewerController@login')->name('viewer.login');
    Route::post('index/viewer/login','ViewerController@login_index')->name('viewer.login_index');
    Route::get('/viewer/registration/page','ViewerController@registration')->name('viewer.registrationindex');
    Route::post('/viewer/registration','ViewerController@registration_store')->name('viewer.store');
    Route::get('/viewer/logout','ViewerController@logout_viewer')->name('viewer.logout');
    Route::get('/viewer/addpost','ViewerController@viewer_addpost')->name('viewer.viewer_addpost');
    Route::get('/viewer/adddiupost','ViewerController@viewer_adddiupost')->name('viewer.viewer_adddiupost');
    Route::post('/viewer/addpost','ViewerController@addpost')->name('viewer.addpost');
    Route::post('/viewer/adddiupost','ViewerController@adddiupost')->name('viewer.adddiupost');
    Route::get('/diu/','DiupostController@home')->name('diu.index');
    Route::get('/diu/category/{id}/posts','DiupostController@catposts')->name('diu.catposts');
    Route::get('diu/single/{id}',['as'=>'diusinglePost', 'uses'=>'DiupostController@single']);

});



Route::group(['middleware' => ['auth']], function () {
    Route::get('/admin/adminindex', function () {
        return view('admin.adminindex');
    });

    Route::get('createcategory', function () {
        return view('admin.category.createcategory');
    });
    Route::resource('cat', 'CatController');
    Route::resource('post', 'PostController');
    Route::resource('diupost', 'DiupostController');
    Route::resource('diucat', 'DiucatController');
    Route::resource('slider', 'SliderController');
    Route::resource('contact', 'ContactController');
    Route::resource('comment', 'CommentController');
    Route::resource('login', 'LoginController');
    Route::resource('user', 'UserController');
    Route::resource('mail', 'MailController');
    Route::get('/admin/userpost', 'ViewerController@adminviewpost')->name('adminviewpost');
    Route::get('/admin/userdiupost', 'ViewerController@adminviewdiupost')->name('adminviewdiupost');
    Route::get('/admin/approve/userpost/{id}', 'ViewerController@approvepost')->name('approvepost');
    Route::get('/admin/approve/userdiupost/{id}', 'ViewerController@approvediupost')->name('approvediupost');

    Route::get('/mail/confirmation/{token}', 'MailController@confirmation')->name('confirmation');
    Route::get('/user/confirmation/{token}', 'UserController@confirmation')->name('confirmation');
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/frontend/layouts/breakingNews.blade.php
<div class="hero-area">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12">
                <!-- Breaking News Widget -->
                <div class="breaking-news-area d-flex align-items-center">
                    <div class="news-title">
                        <p>Latest News</p>
                    </div>
                    <div id="breakingNewsTicker" class="ticker">
                        <ul>
                            <li><a href="{{ route('singlePost',$brknews->id) }}">{{ $brknews->title }}</a></li>
                        </ul>
                    </div>
                </div>

                <!-- Breaking News Widget -->
                <div class="breaking-news-area d-flex align-items-center mt-15">
                    <div class="news-title title2">
                        <p>International</p>
                    </div>
                    <div id="internationalTicker" class="ticker">
                        <ul>
                            @foreach($inter_breaking_posts as $rows)
                            <li><a href="{{ route('singlePost',$rows->id) }}">{{ $rows->title }}</a></li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>

            <!-- Banner -->
            {{--<div class="col-12 col-lg-4">--}}
            {{--<div class="hero-add">--}}
            {{--<a href="#"><img src="img/bg-img/hero-add.gif" alt=""></a>--}}
            {{--</div>--}}
            {{--</div>--}}
        </div>
    </div>
</div>

resources/views/frontend/layouts/footer.blade.php
<footer class="footer-area">

    <!-- Main Footer Area -->
    <div class="main-footer-area">
        <div class="container">
            <div class="row">

                <!-- Footer Widget Area -->
                <div class="col-12 col-sm-6 col-lg-4">
                    <div class="footer-widget-area mt-80">
                        <!-- Footer Logo -->
                        <!-- <div class="footer-logo">
                            <a href="index.html"><img src="{{ asset('ui/frontend/img/core-img/logo.png') }}" alt=""></a>
                        </div> -->
                        <!-- List -->
                        <ul class="list">
                            <li><a href="mailto:contact@youremail.com">contact@youremail.com</a></li>
                            <li><a href="tel:+4352782883884">+43 5278 2883 884</a></li>
                            <li><a href="http://yoursitename.com">www.yoursitename.com</a></li>
                        </ul>
                    </div>
                </div>

                <!-- Footer Widget Area -->
                <div class="col-12 col-sm-6 col-lg-2">
                    <div class="footer-widget-area mt-80">
                        <!-- Title -->
                        <h4 class="widget-title">Politics</h4>
                        <!-- List -->
                        <ul class="list">
                            <li><a href="#">Business</a></li>
                            <li><a href="#">Markets</a></li>
                            <li><a href="#">Tech</a></li>
                            <li><a href="#">Luxury</a></li>
                        </ul>
                    </div>
                </div>

                <!-- Footer Widget Area -->
                <div class="col-12 col-sm-4 col-lg-2">
                    <div class="footer-widget-area mt-80">
                        <!-- Title -->
                        <h4 class="widget-title">Featured</h4>
                        <!-- List -->
                        <ul class="list">
                            <li><a href="#">Football</a></li>
                            <li><a href="#">Golf</a></li>
                            <li><a href="#">Tennis</a></li>
                            <li><a href="#">Motorsport</a></li>
                            <li><a href="#">Horseracing</a></li>
                            <li><a href="#">Equestrian</a></li>
                            <li><a href="#">Sailing</a></li>
                            <li><a href="#">Skiing</a></li>
                        </ul>
                    </div>
                </div>

                <!-- Footer Widget Area -->
                <div class="col-12 col-sm-4 col-lg-2">
                    <div class="footer-widget-area mt-80">
                        <!-- Title -->
                        <h4 class="widget-title">FAQ</h4>
                        <!-- List -->
                        <ul class="list">
                            <li><a href="#">Aviation</a></li>
                            <li><a href="#">Business</a></li>
                            <li><a href="#">Traveller</a></li>
                            <li><a href="#">Destinations</a></li>
                            <li><a href="#">Features</a></li>
                            <li><a href="#">Food/Drink</a></li>
                            <li><a href="#">Hotels</a></li>
                            <li><a href="#">Partner Hotels</a></li>
                        </ul>
                    </div>
                </div>

                <!-- Footer Widget Area -->
                <div class="col-12 col-sm-4 col-lg-2">
                    <div class="footer-widget-area mt-80">
                        <!-- Title -->
                        <h4 class="widget-title">+More</h4>
                        <!-- List -->
                        <ul class="list">
                            <li><a href="#">Fashion</a></li>
                            <li><a href="#">Design</a></li>
                            <li><a href="#">Architecture</a></li>
                            <li><a href="#">Arts</a></li>
                            <li><a href="#">Autos</a></li>
                            <li><a href="#">Luxury</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bottom Footer Area -->
    <div class="bottom-footer-area">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <!-- Copywrite -->
                    <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved 
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- ##### Footer Area Start ##### -->

<!-- ##### All Javascript Files ##### -->
<!-- jQuery-2.2.4 js -->
<script type="text/javascript">
    $('.carousel-3d-controls').mdbCarousel3d();
</script>
<script src="{{ asset('ui/frontend/js/jquery/jquery-2.2.4.min.js') }}"></script>
<!-- Popper js -->
<script src="{{ asset('ui/frontend/js/bootstrap/popper.min.js') }}"></script>
<!-- Bootstrap js -->
<script src="{{ asset('ui/frontend/js/bootstrap/bootstrap.min.js') }}"></script>
<!-- All Plugins js -->
<script src="{{ asset('ui/frontend/js/plugins/plugins.js') }}"></script>
<!-- Active js -->
<script src="{{ asset('ui/frontend/js/active.js') }}"></script>


</body>

</html>

resources/views/frontend/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title -->
    <title>The News Paper - News &amp; Lifestyle Magazine Template</title>

    <!-- Favicon -->
    <link rel="icon" href="{{ asset('ui/frontend/img/core-img/favicon.ico') }}">



    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="{{ asset('ui/frontend/style.css') }}">

</head>

<body>
<!-- ##### Header Area Start ##### -->
<header class="header-area">

    <!-- Top Header Area -->
    <div class="top-header-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="top-header-content d-flex align-items-center justify-content-between">
                        <!-- Logo -->
                        <div class="logo">
                            <div class="quotes_h">
                                <center><div class="weather-box cloud-img" style="width: 24px; height: 24px"><img src="{{ asset('images/cloudy.png') }}" alt=""></center>
                                <h6><center><strong style="color: #fff;">{{$test}} &#8451</strong></center></h6>
                                <h6><center><strong style="color: #fff;">{{ $date }}</strong></center></h6>
                            </div>
                        </div>

                        <!-- Login Search Area -->
                        <div class="login-search-area d-flex align-items-center">
                            <!-- Login -->
                            @php
                                $viewer_name=session('viewer_name')
                            @endphp
                            <?php if($viewer_name != NULL){ ?>
                            <span class="welcome_text" style="margin-right: 415px;margin-top: 13px"> 
                            <h6><strong style="color: #fff;"><i class="fa fa-user">Welcome {{ $viewer_name }}!</i></strong></h6>
                            </span>
                            <div class="login d-flex">
                            <a href="{{ route('viewer.viewer_adddiupost') }}">Add diu post</a>
                            <a href="{{ route('viewer.viewer_addpost') }}">Add post</a>
                            <a href="{{ route('viewer.logout') }}">Logout</a>

                            </div>
                            <?php }else{ ?>
                                <div class="login d-flex">
                                <a href="{{ route('viewer.index') }}">Login</a>
                                <a href="{{ route('viewer.registrationindex') }}">Register</a>
                            </div>
                            <?php }?>
                            
                            <!-- Search Form -->
                            <!-- <div class="search-form">
                                <form action="#" method="post">
                                    <input type="search" name="search" class="form-control" placeholder="Search">
                                    <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
                                </form>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

resources/views/frontend/layouts/navbar.blade.php
<div class="newspaper-main-menu" id="stickyMenu">
    <div class="classy-nav-container breakpoint-off">
        <div class="container">
            <!-- Menu -->
            <nav class="classy-navbar justify-content-between" id="newspaperNav">

                <!-- Logo -->
                <div class="logo">
                    <a href=""><img src="img/core-img/logo.png" alt=""></a>
                </div>

                <!-- Navbar Toggler -->
                <div class="classy-navbar-toggler">
                    <span class="navbarToggler"><span></span><span></span><span></span></span>
                </div>

                <!-- Menu -->
                <div class="classy-menu">

                    <!-- close btn -->
                    <div class="classycloseIcon">
                        <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                    </div>

                    <!-- Nav Start -->
                    <div class="classynav">
                        <ul>
                            <li class="active"><a href="{{ route('layouts.index') }}">Home</a></li>
                            {{--<li><a href="#">Pages</a>--}}
                                {{--<ul class="dropdown">--}}
                                    {{--<li><a href="index.html">Home</a></li>--}}
                                    {{--<li><a href="catagories-post.html">Catagories</a></li>--}}
                                    {{--<li><a href="single-post.html">Single Articles</a></li>--}}
                                    {{--<li><a href="about.html">About Us</a></li>--}}
                                    {{--<li><a href="contact.html">Contact</a></li>--}}
                                    {{--<li><a href="#">Dropdown</a>--}}
                                        {{--<ul class="dropdown">--}}
                                            {{--<li><a href="index.html">Home</a></li>--}}
                                            {{--<li><a href="catagories-post.html">Catagories</a></li>--}}
                                            {{--<li><a href="single-post.html">Single Articles</a></li>--}}
                                            {{--<li><a href="about.html">About Us</a></li>--}}
                                            {{--<li><a href="contact.html">Contact</a></li>--}}
                                        {{--</ul>--}}
                                    {{--</li>--}}
                                {{--</ul>--}}
                            {{--</li>--}}
                            {{--<li><a href="#">Mega Menu</a>--}}
                                {{--<div class="megamenu">--}}
                                    {{--<ul class="single-mega cn-col-4">--}}
                                        {{--<li class="title">Catagories</li>--}}
                                        {{--<li><a href="index.html">Home</a></li>--}}
                                        {{--<li><a href="catagories-post.html">Catagories</a></li>--}}
                                        {{--<li><a href="single-post.html">Single Articles</a></li>--}}
                                        {{--<li><a href="about.html">About Us</a></li>--}}
                                        {{--<li><a href="contact.html">Contact</a></li>--}}
                                    {{--</ul>--}}
                                    {{--<ul class="single-mega cn-col-4">--}}
                                        {{--<li class="title">Catagories</li>--}}
                                        {{--<li><a href="index.html">Home</a></li>--}}
                                        {{--<li><a href="catagories-post.html">Catagories</a></li>--}}
                                        {{--<li><a href="single-post.html">Single Articles</a></li>--}}
                                        {{--<li><a href="about.html">About Us</a></li>--}}
                                        {{--<li><a href="contact.html">Contact</a></li>--}}
                                    {{--</ul>--}}
                                    {{--<ul class="single-mega cn-col-4">--}}
                                        {{--<li class="title">Catagories</li>--}}
                                        {{--<li><a href="index.html">Home</a></li>--}}
                                        {{--<li><a href="catagories-post.html">Catagories</a></li>--}}
                                        {{--<li><a href="single-post.html">Single Articles</a></li>--}}
                                        {{--<li><a href="about.html">About Us</a></li>--}}
                                        {{--<li><a href="contact.html">Contact</a></li>--}}
                                    {{--</ul>--}}
                                    {{--<div class="single-mega cn-col-4">--}}
                                        {{--<!-- Single Featured Post -->--}}
                                        {{--<div class="single-blog-post small-featured-post d-flex">--}}
                                            {{--<div class="post-thumb">--}}
                                                {{--<a href="#"><img src="img/bg-img/23.jpg" alt=""></a>--}}
                                            {{--</div>--}}
                                            {{--<div class="post-data">--}}
                                                {{--<a href="#" class="post-catagory">Travel</a>--}}
                                                {{--<div class="post-meta">--}}
                                                    {{--<a href="#" class="post-title">--}}
                                                        {{--<h6>Pellentesque mattis arcu massa, nec fringilla turpis eleifend id.</h6>--}}
                                                    {{--</a>--}}
                                                    {{--<p class="post-date"><span>7:00 AM</span> | <span>April 14</span></p>--}}
                                                {{--</div>--}}
                                            {{--</div>--}}
                                        {{--</div>--}}

                                        {{--<!-- Single Featured Post -->--}}
                                        {{--<div class="single-blog-post small-featured-post d-flex">--}}
                                            {{--<div class="post-thumb">--}}
                                                {{--<a href="#"><img src="img/bg-img/24.jpg" alt=""></a>--}}
                                            {{--</div>--}}
                                            {{--<div class="post-data">--}}
                                                {{--<a href="#" class="post-catagory">Politics</a>--}}
                                                {{--<div class="post-meta">--}}
                                                    {{--<a href="#" class="post-title">--}}
                                                        {{--<h6>Augue semper congue sit amet ac sapien. Fusce consequat.</h6>--}}
                                                    {{--</a>--}}
                                                    {{--<p class="post-date"><span>7:00 AM</span> | <span>April 14</span></p>--}}
                                                {{--</div>--}}
                                            {{--</div>--}}
                                        {{--</div>--}}
                                    {{--</div>--}}
                                {{--</div>--}}
                            {{--</li>--}}
                            @foreach($cat as $rows)
                                <li><a href="{{ route('categoryPost',$rows->id) }}">{{ $rows->name }}</a></li>
                            @endforeach
                            <li><a href="{{ route('crawl.index') }}">Prothom Alo</a></li>
                            <li><a href="#">Diu</a>
                                <ul class="dropdown">
                                    <li><a href="{{ route('diu.index') }}">Home</a></li>
                                    @foreach($diucat as $rows)
                                        <li><a href="{{ route('diu.catposts',$rows->id) }}">{{ $rows->name }}</a></li>
                                    @endforeach

                                </ul>
                            </li>
                            {{--<li><a href="#">About Us</a></li>--}}
                            {{--<li><a href="contact.html">Contact</a></li>--}}
                            @php
                                $viewer_id=session('viewer_id')
                            @endphp
                            <?php if($viewer_id != NULL){ ?>
                            
                            <?php } ?>

                        </ul>
                    </div>
                    <!-- Nav End -->
                </div>
            </nav>
        </div>
    </div>
</div>
</header>